# General config
show_progress: False
use_async: False

# DirReader Config
input_dir: data/
only_suffixs: .pdf
recursive: True
num_files_limit: 10

verbose: False
response_mode: tree_summarize
streaming: False

defaults:
  - retrieve: sparse
  - splitter: sentence