artifacts_root: artifacts

reader_config: 
  file_path: rag/data/
  only_suffixs: .pdf
  encoding: null
  recursive: False
  num_files_limit: null
  show_progress: False
  num_workers: null
  
milvus_config: 
  host: localhost
  port: 19530
  address: null
  uri: null
  user: null
  collection_name: MilvusCollection
  embedding_dim: 384
  embedding_field: embedding
  primary_field: doc_id
  text_field: null
  consistency_level: null
  overwrite: True
  search_params: 
    metric_type: COSINE
    offset: 0
    ignore_growing: False
    params: 
      nprobe: 10
  index_params: 
    metric_type: COSINE
    index_type: IVF_FLAT
    params: 
      nlist: 1024

split_config: 
  splitter_mode: sentence
  model_name_tokenizer: BAAI/bge-small-en
  separator: " "
  chunk_size: 256
  chunk_overlap: 20
  # for sentence splitter 
  paragraph_separator: null
  secondary_chunking_regex: null
  # for token splitter
  backup_separators: null