# Support bm25/table
retriever_mode: bm25
similarity_top_k: 5
# Table mode: simple, rake, llm algorithms
keyword_table_mode: simple
max_keywords_per_chunk: null
max_keywords_per_query: 10
num_chunks_per_query: 10
# Genereation config for llm if using llm algorithm
context_window: 3900
early_stopping: True